
services:
  spacebar:
    image: botans.org:5000/spacebarchat:0.0.1
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      DATABASE: postgres://spacebar:password@db:5432/spacedb
      PORT: "3001"

  db:
    image: postgres:15.8-alpine3.20
    environment:
      - POSTGRES_USER=spacebar
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=spacedb
    ports:
      - '5432:5432'
    volumes: 
      - '$PWD/postgresql:/var/lib/postgresql/data'
